import {
  Activity,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Book,
  BookOpen,
  Briefcase,
  Calendar,
  Check,
  Coffee,
  Compass,
  Copy,
  ExternalLink,
  Feather,
  Gamepad2,
  House,
  Info,
  Layers,
  Map,
  MapPin,
  Move,
  LocateFixed,
  RotateCcw,
  Rss,
  Search,
  Share2,
  Sunrise,
  Tag,
  User,
  Volume2,
  VolumeX,
  X,
} from "lucide-react";

// Explicit imports keep the full Lucide catalogue out of the client bundle.
export const icons = {
  activity: Activity,
  archive: Archive,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-right": ArrowUpRight,
  book: Book,
  "book-open": BookOpen,
  briefcase: Briefcase,
  calendar: Calendar,
  check: Check,
  coffee: Coffee,
  compass: Compass,
  copy: Copy,
  "external-link": ExternalLink,
  feather: Feather,
  gamepad: Gamepad2,
  home: House,
  info: Info,
  layers: Layers,
  map: Map,
  "map-pin": MapPin,
  move: Move,
  locate: LocateFixed,
  "rotate-ccw": RotateCcw,
  rss: Rss,
  search: Search,
  "share-2": Share2,
  sunrise: Sunrise,
  tag: Tag,
  user: User,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  x: X,
} as const;

export type IconName = keyof typeof icons;
